<a href="https://colab.research.google.com/github/mdamron2022/labs-maryndamron/blob/main/Lab_4_STATS_Maryn_Damron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([1,2,3,4])

In [3]:
# population

In [4]:
np.sum(x)

10

In [5]:
x.shape[0]

4

In [6]:
def mean(x):
    return np.sum(x)/x.shape[0]

In [7]:
mean(x)

2.5

In [8]:
x

array([1, 2, 3, 4])

In [9]:
x - mean(x)

array([-1.5, -0.5,  0.5,  1.5])

In [10]:
(x - mean(x))**2

array([2.25, 0.25, 0.25, 2.25])

In [11]:
 def var(x):
    return mean((x - mean(x))**2)

In [12]:
def std(x):
    return np.sqrt(var(x))

In [13]:
mean(x)

2.5

In [14]:
var(x)

1.25

In [15]:
std(x)

1.118033988749895

RANDOM # GENERATOR

In [16]:
m = 75                 # multiplier
b = 74                 # increment
n = 65537              # modulus 

In [17]:
X = 58      # seed value

In [18]:
X = np.zeros(5000,)

In [19]:
X = (m * x + b) % n