<a href="https://colab.research.google.com/github/mdamron2022/labs-maryndamron/blob/main/Lab_3_STATS_Maryn_Damron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
choice = "apple"

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")


You choose apples.


In [ ]:
choice = "orange"

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")
    

You choose oranges.


In [ ]:
# choice = input("Please enter your choice (i.e. apple): ")

In [ ]:
choice

'orange'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


    -

CARDS:

-

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([36, 43, 16, 29,  3, 31,  2, 28,  1,  0, 45, 26, 50, 30, 13, 44, 18,
       23, 51,  6, 17, 40, 22, 27,  8, 49, 10,  7, 25, 34,  4, 46, 33, 47,
       42, 15, 35, 21, 11, 24, 20, 48, 41, 38,  5,  9, 39, 14, 32, 19, 37,
       12])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards[0]

49

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Jack of Diamonds', 'Nine of Hearts', 'Nine of Clubs')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Diamonds
Nine of Hearts
Jack of Hearts
Three of Clubs
Six of Hearts


In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
suit[i]

'p'

In [ ]:
card[j]

'j'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)